spring.application.name=NewsLetterCRUD
git
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/news
spring.datasource.username=root
spring.datasource.password=asnit123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.security=DEBUG

mail.address=furnituremandu@gmail.com
mail.key=vqos ibnf oewq dqrj
app.jwt.refresh-token-expiration=604800000
app.jwt.refresh-threshold=120000
app.jwt.secret=haljldfskjakljfldasjlfjaslfsjaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfjsaldkfj
app.jwt.auth-expiration=900000



debug=true